Models/Branch.cs
namespace BT139.Models
{
	public enum Branch
	{
		IT,
		BE,
		CE,
		EE
	}
}

Models/ErrorViewModel.cs
namespace BT139.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Gender.cs
namespace BT139.Models
{
	public enum Gender
	{
		Male,
		Female
	}
}

Models/MenuItem.cs
namespace BT139.Models
{
    public class MenuItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
    }
}

Models/Student.cs
namespace BT139.Models
{
	public class Student
	{
		public int Id { get; set; }//Mã sinh viên
		public string? Name { get; set; } //Họ tên
		public string? Email { get; set; } //Email
		public string? Password { get; set; }//Mật khẩu
		public Branch? Branch { get; set; }//Ngành học
		public Gender? Gender { get; set; }//Giới tính
		public bool IsRegular { get; set; }//Hệ: true-chính qui, false-phi cq
		public string? Address { get; set; }//Địa chỉ
		public DateTime DateOfBorth { get; set; }//Ngày sinh
	}
}

Controllers/HomeController.cs
using BT139.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BT139.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/StudentController.cs
using BT139.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BT139.Controllers
{
	public class StudentController : Controller
	{
		private List<Student> listStudents = new List<Student>();
		public StudentController()
		{
			//Tạo danh sách sinh viên với 4 dữ liệu mẫu
			listStudents = new List<Student>()
			{
				new Student() { Id = 101, Name = "Hải Nam", Branch = Branch.IT,
								Gender = Gender.Male, IsRegular=true,
								Address = "A1-2018", Email = "nam@g.com" },

				new Student() { Id = 102, Name = "Minh Tú", Branch = Branch.BE,
								Gender = Gender.Female, IsRegular=true,
								Address = "A1-2019", Email = "tu@g.com" },

				new Student() { Id = 103, Name = "Hoàng Phong", Branch = Branch.CE,
								Gender = Gender.Male, IsRegular=false,
								Address = "A1-2020", Email = "phong@g.com" },

				new Student() { Id = 104, Name = "Xuân Mai", Branch = Branch.EE,
								Gender = Gender.Female, IsRegular = false,
								Address = "A1-2021", Email = "mai@g.com" }

			};
		}
        [HttpGet("/Admin/Student/List")]
        [HttpGet("/")]
        public IActionResult Index()
		{
			return View(listStudents);
		}
        [HttpGet]
        public IActionResult Create()
        {
            //lấy danh sách các giá trị Gender để hiển thị radio button trên form
            ViewBag.AllGenders = Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();
            //lấy danh sách các giá trị Branch để hiển thị select-option trên form
            //Để hiển thị select-option trên View cần dùng List<SelectListItem>
            ViewBag.AllBranches = new List<SelectListItem>()
			{
				new SelectListItem { Text = "IT", Value = "1" },
				new SelectListItem { Text = "BE", Value = "2" },
				new SelectListItem { Text = "CE", Value = "3" },
				new SelectListItem { Text = "EE", Value = "4" }
			};
            return View();
        }
        [HttpPost]
        public IActionResult Create(Student s)
        {
            s.Id = listStudents.Last<Student>().Id + 1;
            listStudents.Add(s);
            return View("Index", listStudents);
        }
    }
}

ViewComponents/RenderViewComponent.cs
using BT139.Models;
using Microsoft.AspNetCore.Mvc;

namespace BT139.ViewComponents
{
    public class RenderViewComponent:ViewComponent
    {
        private List<MenuItem> MenuItems = new List<MenuItem>();
        public RenderViewComponent()
        {
            MenuItems = new List<MenuItem>()
            {
                new MenuItem() { Id=1, Name = "Branches", Link = "Branches/List" },
                new MenuItem() { Id=2, Name = "Students", Link = "Students/List" },
                new MenuItem() { Id=3, Name = "Subjects", Link = "Subjects/List" },
                new MenuItem() { Id=4, Name = "Courses", Link = "Courses/List" }
            };

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("RenderLeftMenu", MenuItems);
        }
            
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/Components/Render/RenderLeftMenu.cshtml
@model IEnumerable<MenuItem>
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="index.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">Addons</div>
                @foreach(var i in Model)
                {
                    <a class="nav-link" href="@i.Link">
                        <div class="sb-nav-link-icon"><i class="fas-chart-area"></i></div>
                        @i.Name
                    </a>
                }
                <a class="nav-link" href="charts.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Branches
                </a>
                <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                    Students
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as: MyAccount</div>
        </div>
    </nav>
</div>

Views/Shared/Footer.cshtml
<div class="container-fluid px-4">
    <div class="d-flex align-items-center justify-content-between small">
        <div class="text-muted">Copyright &copy; 2023</div>
    </div>
</div>

Views/Shared/LeftMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="index.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="charts.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Branches
                </a>
                <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                    Students
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as: MyAccount</div>
        </div>
    </nav>
</div>

Views/Shared/Main.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container-fluid px-4">
    <h1 class="mt-4">Dashboard</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Student List
        </div>
        <div class="card-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>DoB</th>
                        <th>Branch</th>
                        <th>Gender</th>
                        <th>Type</th>
                        <th>Address</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>DoB</th>
                        <th>Branch</th>
                        <th>Gender</th>
                        <th>Type</th>
                        <th>Address</th>
                        <th>Email</th>
                    </tr>
                </tfoot>
                <tbody>
                    <tr>
                        <td>101</td>
                        <td>H&#x1EA3;i Nam</td>
                        <td>1/1/0001 12:00:00 AM</td>
                        <td>CNTT</td>
                        <td>Nam</td>
                        <td>Ch&#xED;nh quy</td>
                        <td>A1-2018</td>
                        <td>nam@g.com</td>
                    </tr>
                    <tr>
                        <td>102</td>
                        <td>Minh T&#xFA;</td>
                        <td>1/1/0001 12:00:00 AM</td>
                        <td>Kinh t&#x1EBF;</td>
                        <td>N&#x1EEF;</td>
                        <td>Ch&#xED;nh quy</td>
                        <td>A1-2019</td>
                        <td>tu@g.com</td>
                    </tr>
                    <tr>
                        <td>103</td>
                        <td>Ho&#xE0;ng Phong</td>
                        <td>1/1/0001 12:00:00 AM</td>
                        <td>C&#xF4;ng tr&#xEC;nh</td>
                        <td>Nam</td>
                        <td>Phi ch&#xED;nh quy</td>
                        <td>A1-2020</td>
                        <td>phong@g.com</td>
                    </tr>
                    <tr>
                        <td>104</td>
                        <td>Xu&#xE2;n Mai</td>
                        <td>1/1/0001 12:00:00 AM</td>
                        <td>&#x110;i&#x1EC7;n - &#x110;i&#x1EC7;n t&#x1EED;</td>
                        <td>N&#x1EEF;</td>
                        <td>Phi ch&#xED;nh quy</td>
                        <td>A1-2021</td>
                        <td>mai@g.com</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/Shared/MyLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Management System</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"></script>
</head>
<body class="sb-nav-fixed">
    <!-- Begin Top nav -->
    <partial name="TopNav" />
    <!-- End Top nav -->
    <div id="layoutSidenav">
        <!-- Begin Left menu -->
        <div id="layoutSidenav_nav">
            <partial name="LeftMenu" />
        </div>
        <!-- End Left menu -->
        <!-- Begin Right content -->
        <div id="layoutSidenav_content">
            <!-- Begin Main -->
            <main>
                @RenderBody()
            </main>
            <!-- End Main -->
            <!-- Begin Footer -->
            <footer class="py-4 bg-light mt-auto">
                <partial name="Footer" />
            </footer>
            <!-- End Footer -->
        </div>
        <!-- End Right content -->
    </div>
    <script src="js/scripts.js"></script>
    @RenderSection("Scripts", required:false);
</body>
</html>

Views/Shared/MyLayoutHelper.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - Admin</title>
    <title>@ViewData["Title"] - Management System</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"></script>
</head>
<body class="sb-nav-fixed">
    <!-- Begin Top nav -->
    <partial name="TopNav" />
    <!-- End Top nav -->
    <div id="layoutSidenav">
        <!-- Begin Left menu -->
        <div id="layoutSidenav_nav">
            @await Component.InvokeAsync("Render");
        </div>
        <!-- End Left menu -->
        <!-- Begin Right content -->
        <div id="layoutSidenav_content">
            <!-- Begin Main -->
            <main>
                @RenderBody()
            </main>
            <!-- End Main -->
            <!-- Begin Footer -->
            <footer class="py-4 bg-light mt-auto">
                <partial name="Footer" />
            </footer>
            <!-- End Footer -->
        </div>
        <!-- End Right content -->
    </div>
    <script src="js/scripts.js"></script>
    @RenderSection("Scripts", required:false);
</body>
</html>

Views/Shared/TopNav.cshtml
<!-- Begin Top nav -->
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="">Management System</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#!">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- End Top nav -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BT139</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BT139.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BT139</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BT139 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Student
<div>
    <form asp-controller="Student" asp-action="Create" method="post" class="mt-3">
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" placeholder="Họ tên">
            </div>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Email" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Email" class="form-control" placeholder="Email">
            </div>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Password" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Password" class="form-control" placeholder="Password">
            </div>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Branch" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <select asp-for="Branch" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<Branch>()"></select>
                @*<select asp-for="Gender" asp-items="ViewBag.AllBranches"></select>*@
            </div>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="IsRegular" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input type="checkbox" class="custom-control-input" asp-for="IsRegular">
            </div>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="DateOfBorth" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="DateOfBorth" class="form-control">
            </div>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Gender" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                @foreach (var gender in ViewBag.AllGenders)
                {
                    <label class="radio-inline">
                        <input type="radio" asp-for="Gender" value="@gender"
                               id="Gender@(gender)" />@gender<br />

                    </label>
                }
            </div>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
<textarea asp-for="Address" class="form-control"
          placeholder="Địa chỉ"></textarea>

            </div>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>
    </form>
</div>

Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Student List";
    Layout = "~/Views/Shared/MyLayoutHelper.cshtml";
}
@section Scripts{
    <script>
        var table = document.querySelector("table");
        table.onclick = function onTableClick() {
            table.style = "background-color: yeallow;"
        }
    </script>
}
@model IEnumerable<Student>
<a asp-action="Create" class="btn btn-primary">Create Student</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Họ tên</th>
            <th>Ngày sinh</th>  
            <th>Ngành</th>
            <th>Giới tính</th>
            <th>Hệ ĐT</th>
            <th>Địa chỉ</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.Id</td>
                <td>@s.Name</td>
                <td>@s.DateOfBorth</td>
                @{
                    string str = "";
                    switch (s.Branch)

                    {

                        case Branch.IT:
                            str = "CNTT";
                            break;
                        case Branch.BE:
                            str = "Kinh tế";
                            break;
                        case Branch.CE:
                            str = "Công trình";

                            break;
                        case Branch.EE:
                            str = "Điện - Điện tử";
                            break;
                    }
                }
                <td>@str</td>
                <td>@(s.Gender == Gender.Male ? "Nam" : "Nữ")</td>
                <td>@(s.IsRegular ? "Chính quy" : "Phi chính quy")</td>
                <td>@s.Address</td>
                <td>@s.Email</td>
            </tr>
        }
    </tbody>
</table>